version: "3.9"
services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    container_name: titanic_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/models/trained_model
    volumes:
      - ../../models:/models:ro
  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    container_name: titanic_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

